addpath envs
addpath filters
addpath base

%% ------ CONFIG VARS

fig = figure;
plt = subplot(311);

cur_note = def_note();
cur_time = def_timesig();
cur_track = {[]};%%current track is a cell array of the list of notes
cur_track_num = 1;

cur_octave = 4;

%% ------ Keyboard config

%panel for the keys
key_panel = uipanel(fig, ...
    'Position', [0.05 0.35 0.9 0.3]);

cur_keys = 440 * 2.^((cur_octave - 4) + ([1:25] - 10) / 12);

key_press = @(k) strcat('cur_note.freq = cur_keys(',...
    num2str(k),');',...
    'sound(write_note(cur_note, cur_time));');

w_key = @(pos) ...
    uicontrol(key_panel,...
    'Style', 'pushbutton',...
    'FontUnits', 'normalized',...
    'Units', 'normalized', ...
    'Position', [pos (1/18) 0.9]);

b_key = @(pos) ...
    uicontrol(key_panel,...
    'Style', 'pushbutton',...
    'FontUnits', 'normalized',...
    'Units', 'normalized', ...
    'BackgroundColor', 'black', ...
    'Position', [pos (1/20) 0.45]);

white_keys = [1 3 5 6 8 10 12 13 15 17 18 20 22 24 25];
black_keys = [2 4 7 9 11 14 16 19 21 23];

for ind = 1:length(white_keys)
    h_pos = (1/17) * ind;
    keys(white_keys(ind)) = w_key([h_pos 0.05]);
    keys(white_keys(ind)).Callback = key_press(white_keys(ind));
end

black_key_pos = [2 4 8 10 12 16 18 22 24 26];

for ind = 1:length(black_keys)
    h_pos = (1/34) * black_key_pos(ind) + 1/34;
    keys(black_keys(ind)) = b_key([h_pos 0.45]);
    keys(black_keys(ind)).Callback = key_press(black_keys(ind));
end

% Change octave buttons

l_octave = uicontrol(key_panel,...
    'String', '<',...
    'Style', 'pushbutton',...
    'Units', 'normalized', ...
    'BackgroundColor', [0.5 0.5 0.5], ...
    'Position', [0 0.05 (1/18) 0.9],...
    'Callback', 'cur_octave = cur_octave - 1;cur_keys = 440 * 2.^((cur_octave - 4) + ([1:25] - 10) / 12);');

r_octave = uicontrol(key_panel,...
    'String', '>',...
    'Style', 'pushbutton',...
    'Units', 'normalized', ...
    'BackgroundColor', [0.5 0.5 0.5], ...
    'Position', [16/17 0.05 (1/18) 0.9], ...
    'Callback', 'cur_octave = cur_octave + 1;cur_keys = 440 * 2.^((cur_octave - 4) + ([1:25] - 10) / 12);');

%% -------- PLAYBACK PANEL

playback_panel = uipanel(fig, ...
    'Title', 'Playback',...
    'Position', [0.7 0.03 0.25 0.30]);

save_note = uicontrol(playback_panel,...
    'String', 'Save note',...
    'Style', 'pushbutton',...
    'Units', 'normalized',...
    'Position', [0.05 0.7 0.4 0.25], ...
    'Callback', ...
    ['cur_track{cur_track_num} = [cur_track{cur_track_num} cur_note];' ...
    'update_plot(cur_track{cur_track_num});']);

delete_note = uicontrol(playback_panel,...
    'String', 'Delete note',...
    'Style', 'pushbutton',...
    'Units', 'normalized',...
    'Position', [0.5 0.7 0.4 0.25], ...
    'Callback', ...
    ['cur_note = cur_track{cur_track_num}(end);' ...
    'cur_track{cur_track_num}(end) = [];' ...
    'update_plot(cur_track{cur_track_num});']);

play_track = uicontrol(playback_panel,...
    'String', 'Play Current track',...
    'Style', 'pushbutton',...
    'Units', 'normalized',...
    'Position', [0.05 0.4 0.4 0.25], ...
    'Callback', ...
    'sound(track_to_sig(cur_track{cur_track_num}, cur_time));');
    
play_all = uicontrol(playback_panel,...
    'String', 'Play all tracks',...
    'Style', 'pushbutton',...
    'Units', 'normalized',...
    'Position', [0.5 0.4 0.4 0.25], ...
    'Callback', ...
    'sound(all_track_to_sig(cur_track, cur_time));');

%% -------- NOTE CONFIG PANEL

note_conf_panel = uipanel(fig, ...
    'Title', 'Note config',...
    'Position', [0.4 0.03 0.25 0.30]);

% note length config

note_length_gp = uibuttongroup(note_conf_panel,...
    'Title', 'Beats',...
    'Position', [0.02 0.58 0.96 0.4]);

beat_key_gen = @(pos, dur, cb) uicontrol(note_length_gp,...
    'Style', 'radiobutton', ...
    'String', num2str(dur),...
    'Units', 'normalized',...
    'Position', pos,...
    'Callback', cb);

beat_key(1) = beat_key_gen([0.05 0.65 0.45 0.3], 1,...
    'cur_note.beats = 1');

beat_key(2) = beat_key_gen([0.05 0.35 0.45 0.3], 1/2,...
    'cur_note.beats = 1/2');

beat_key(3) = beat_key_gen([0.05 0.05 0.45 0.3], 1/4,...
    'cur_note.beats = 1/4');

beat_key(4) = beat_key_gen([0.55 0.65 0.45 0.3], 2,...
    'cur_note.beats = 2');

beat_key(5) = beat_key_gen([0.55 0.35 0.45 0.3], 4,...
    'cur_note.beats = 4');

% dynamics config

dynamics_title = uicontrol(note_conf_panel,...
    'String', 'Dynamics',...
    'Style', 'text',...
    'Units', 'normalized',...
    'Position', [0.05 0.48 0.9 0.1]);

dynamics_p = uicontrol(note_conf_panel,...
    'String', 'p',...
    'Style', 'text',...
    'Units', 'normalized',...
    'Position', [0.05 0.40 0.2 0.1]);

dynamics_m = uicontrol(note_conf_panel,...
    'String', 'm',...
    'Style', 'text',...
    'Units', 'normalized',...
    'Position', [0.38 0.40 0.2 0.1]);

dynamics_f = uicontrol(note_conf_panel,...
    'String', 'f',...
    'Style', 'text',...
    'Units', 'normalized',...
    'Position', [0.7 0.40 0.2 0.1]);

dynamics_slider = uicontrol(note_conf_panel,...
    'Style', 'slider',...
    'Units', 'normalized',...
    'Position', [0.05 0.3 0.9 0.1], ...
    'Min', 0,...
    'Max', 1,...
    'Value', 0.5,...
    'Callback', ...
    'cur_note.scale = dynamics_slider.Value');

% Time sig config

bpm_lab = uicontrol(note_conf_panel,...
    'String', 'bpm',...
    'Style', 'text',...
    'Units', 'normalized',...
    'Position', [0.15 0.15 0.2 0.1]);

bpm_box = uicontrol(note_conf_panel,...
    'Style', 'edit',...
    'Units', 'normalized',...
    'Position', [0.05 0.05 0.45 0.1],...
    'String', '4',...
    'Callback',...
    'cur_time.bpm = str2num(bpm_box.String);');

tempo_lab = uicontrol(note_conf_panel,...
    'String', 'tempo',...
    'Style', 'text',...
    'Units', 'normalized',...
    'Position', [0.65 0.15 0.2 0.1]);

tempo_box = uicontrol(note_conf_panel,...
    'Style', 'edit',...
    'Units', 'normalized',...
    'Position', [0.5 0.05 0.45 0.1],...
    'String', '90',...
    'Callback',...
    'cur_time.tempo = str2num(tempo_box.String);');

%% ---------- EFFECTS

effects_panel = uipanel(fig, ...
    'Title', 'Effects',...
    'Position', [0.05 0.03 0.30 0.30]);

%% effects groups

effect_gp(1) = uibuttongroup(effects_panel,...
    'Visible' , 'on',...
    'Title', 'Envelopes',...
    'Position', [0.02 0.02 0.96 0.9]);

effect_gp(2) = uibuttongroup(effects_panel,...
    'Visible' , 'off',...
    'Title', 'Filters',...
    'Position', [0.02 0.02 0.96 0.9]);

effect_gp(3) = uibuttongroup(effects_panel,...
    'Visible' , 'off',...
    'Title', 'Vibrato',...
    'Position', [0.02 0.02 0.96 0.9]);

total_effects = 3;
cur_effect = 0;
next_effect = @(tot, cur) mod(cur + 1, tot);
prev_effect = @(tot, cur) mod(cur - 1, tot);

next_effect_but = uicontrol(effects_panel,...
    'String', '>',...
    'Style', 'pushbutton',...
    'Units', 'normalized',...
    'Position', [0.5 0.92 0.4 0.08], ...
    'Callback', ...
    ['effect_gp(cur_effect + 1).Visible = ''off'';',...
    'cur_effect = next_effect(total_effects, cur_effect);',...
    'effect_gp(cur_effect + 1).Visible = ''on'';']);

prev_effect_but = uicontrol(effects_panel,...
    'String', '<',...
    'Style', 'pushbutton',...
    'Units', 'normalized',...
    'Position', [0.02 0.92 0.4 0.08], ...
    'Callback', ...
    ['effect_gp(cur_effect + 1).Visible = ''off'';',...
    'cur_effect = prev_effect(total_effects, cur_effect);',...
    'effect_gp(cur_effect + 1).Visible = ''on'';']);

%% VIBRATO EFFECTS

vib_amp_text = uicontrol(effect_gp(3),...
    'String', 'Vibrato Amplitude',...
    'Style', 'text',...
    'Units', 'normalized',...
    'Position', [0.05 0.80 0.9 0.1]);

vibrato_amp = uicontrol(effect_gp(3),...
    'Style', 'slider',...
    'Units', 'normalized',...
    'Position', [0.05 0.60 0.9 0.1], ...
    'Min', 0,...
    'Max', 8,...
    'Value', 0,...
    'Callback', ...
    'cur_note.vib_amp = vibrato_amp.Value');

vib_freq_text = uicontrol(effect_gp(3),...
    'String', 'Vibrato Frequency',...
    'Style', 'text',...
    'Units', 'normalized',...
    'Position', [0.05 0.4 0.9 0.1]);

vibrato_freq = uicontrol(effect_gp(3),...
    'Style', 'slider',...
    'Units', 'normalized',...
    'Position', [0.05 0.2 0.9 0.1], ...
    'Min', 0,...
    'Max', 16,...
    'Value', 5,...
    'Callback', ...
    'cur_note.vib_freq = vibrato_freq.Value');
