addpath envs
addpath filters
addpath base

%% ------ CONFIG VARS

fig = figure;
plt = subplot(311);

cur_note = def_note();
cur_time = def_timesig();
cur_track = {[]};%%current track is a cell array of the list of notes
cur_track_num = 1;

cur_octave = 4;

%% ------ Keyboard config

%panel for the keys
key_panel = uipanel(fig, ...
    'Position', [0.05 0.35 0.9 0.3]);

cur_keys = 440 * 2.^((cur_octave - 4) + ([1:25] - 10) / 12);

key_press = @(k) strcat('cur_note.freq = cur_keys(',...
    num2str(k),');',...
    'sound(write_note(cur_note, cur_time));');

w_key = @(pos) ...
    uicontrol(key_panel,...
    'Style', 'pushbutton',...
    'FontUnits', 'normalized',...
    'Units', 'normalized', ...
    'Position', [pos (1/18) 0.9]);

b_key = @(pos) ...
    uicontrol(key_panel,...
    'Style', 'pushbutton',...
    'FontUnits', 'normalized',...
    'Units', 'normalized', ...
    'BackgroundColor', 'black', ...
    'Position', [pos (1/20) 0.45]);

white_keys = [1 3 5 6 8 10 12 13 15 17 18 20 22 24 25];
black_keys = [2 4 7 9 11 14 16 19 21 23];

for ind = 1:length(white_keys)
    h_pos = (1/17) * ind;
    keys(white_keys(ind)) = w_key([h_pos 0.05]);
    keys(white_keys(ind)).Callback = key_press(white_keys(ind));
end

black_key_pos = [2 4 8 10 12 16 18 22 24 26];

for ind = 1:length(black_keys)
    h_pos = (1/34) * black_key_pos(ind) + 1/34;
    keys(black_keys(ind)) = b_key([h_pos 0.45]);
    keys(black_keys(ind)).Callback = key_press(black_keys(ind));
end

% Change octave buttons

l_octave = uicontrol(key_panel,...
    'String', '<',...
    'Style', 'pushbutton',...
    'Units', 'normalized', ...
    'BackgroundColor', [0.5 0.5 0.5], ...
    'Position', [0 0.05 (1/18) 0.9],...
    'Callback', 'cur_octave = cur_octave - 1;cur_keys = 440 * 2.^((cur_octave - 4) + ([1:25] - 10) / 12);');

r_octave = uicontrol(key_panel,...
    'String', '>',...
    'Style', 'pushbutton',...
    'Units', 'normalized', ...
    'BackgroundColor', [0.5 0.5 0.5], ...
    'Position', [16/17 0.05 (1/18) 0.9], ...
    'Callback', 'cur_octave = cur_octave + 1;cur_keys = 440 * 2.^((cur_octave - 4) + ([1:25] - 10) / 12);');

%% -------- PLAYBACK PANEL

playback_panel = uipanel(fig, ...
    'Title', 'Playback',...
    'Position', [0.7 0.03 0.25 0.30]);

save_note = uicontrol(playback_panel,...
    'String', 'Save note',...
    'Style', 'pushbutton',...
    'Units', 'normalized',...
    'Position', [0.05 0.7 0.4 0.25], ...
    'Callback', ...
    ['cur_track{cur_track_num} = [cur_track{cur_track_num} cur_note];' ...
    'update_plot(cur_track{cur_track_num});']);

delete_note = uicontrol(playback_panel,...
    'String', 'Delete note',...
    'Style', 'pushbutton',...
    'Units', 'normalized',...
    'Position', [0.5 0.7 0.4 0.25], ...
    'Callback', ...
    ['cur_note = cur_track{cur_track_num}(end);' ...
    'cur_track{cur_track_num}(end) = [];' ...
    'update_plot(cur_track{cur_track_num});']);

play_track = uicontrol(playback_panel,...
    'String', 'Play Current track',...
    'Style', 'pushbutton',...
    'Units', 'normalized',...
    'Position', [0.05 0.4 0.4 0.25], ...
    'Callback', ...
    'sound(track_to_sig(cur_track{cur_track_num}, cur_time));');

%% -------- NOTE CONFIG PANEL

note_conf_panel = uipanel(fig, ...
    'Title', 'Note config',...
    'Position', [0.4 0.03 0.25 0.30]);

note_length_gp = uibuttongroup(note_conf_panel,...
    'Title', 'Beats',...
    'Position', [0.02 0.5 0.96 0.4]);

beat_key_gen = @(pos, dur, cb) uicontrol(note_length_gp,...
    'Style', 'radiobutton', ...
    'String', num2str(dur),...
    'Units', 'normalized',...
    'Position', pos,...
    'Callback', cb);

beat_key(1) = beat_key_gen([0.05 0.65 0.45 0.3], 1,...
    'cur_note.beats = 1');

beat_key(2) = beat_key_gen([0.05 0.35 0.45 0.3], 1/2,...
    'cur_note.beats = 1/2');

beat_key(3) = beat_key_gen([0.05 0.05 0.45 0.3], 1/4,...
    'cur_note.beats = 1/4');

beat_key(4) = beat_key_gen([0.55 0.65 0.45 0.3], 2,...
    'cur_note.beats = 2');

beat_key(5) = beat_key_gen([0.55 0.35 0.45 0.3], 4,...
    'cur_note.beats = 4');
