env_names = {...
    'None',...
    'Hanning',...
    'Inverse',...
    'Poisson',...
    'Power'};

env_funcs = {...
    @(t) ones(size(t)),...
    hanning_env(),...
    inv_gen(10),...
    pois_gen(6),...
    pow_gen(-2, 5)};
