env_names = {...
    'None',...
    'Hanning',...
    'Inverse',...
    'Poisson',...
    'Power',...
    'Saw Tremolo',...
    'SIne Tremolo'};

env_funcs = {...
    @(t) ones(size(t)),...
    hanning_env(),...
    inv_gen(10),...
    pois_gen(6),...
    pow_gen(-2, 5),...
    @(t) mod([1:length(t)], 1000) / 1000,...
    @(t) sin([1:length(t)] / 200)};
