violin_env = adsr_gen(...
    [0.15 0.65],...
    [0.5 0.5],...
    [0.95 0.6]);

piano_env = adsr_gen(...
    [0.02 1],...
    [0.6 0.5],...
    [0.86 0.4]);

flute_env = adsr_gen(...
    [0.23 0.84],...
    [0.57 0.5],...
    [0.88 0.5]);

presets_names = {...
    'None',...
    'Violin Legato',...
    'E Piano',...
    'Xylophone',...
    'Flute',...
    'Guitar'};

presets_timbres = {
    0,...
    4.0,...
    [0.15, 0.4],...
    0,...
    0.2,...
    5};

presets_envs = {
    @(t) ones(size(t)),...
    violin_env,...
    piano_env,...
    pow_gen(-2, 5),...
    flute_env,...
    pow_gen(-2, 5)};
