violin_env = adsr_gen(...
    [0.15 0.65],...
    [0.5 0.5],...
    [0.95 0.6]);

piano_env = adsr_gen(...
    [0.02 1],...
    [0.6 0.5],...
    [0.86 0.4]);

presets_names = {...
    'None',...
    'Violin Legato',...
    'E Piano'};

presets_timbres = {
    0,...
    4.0,...
    [0.15, 0.4]};

presets_envs = {
    @(t) ones(size(t)),...
    violin_env,...
    piano_env};

