filter_names = {...
    'None',...
    'Frequency Shift',...
    'Low Pass',...
    'High Pass',...
    'Square',...
    'Cube',...
    'Floor'};

filter_funcs = {...
    @(c, s) s,...
    @b_freq_shift,...
    @low_pass,...
    @high_pass,...
    @(c, s) s .* abs(s),...
    @(c, s) s.^3,...
    @(c, s) floor(c * s) / c};
